-- DROP TABLE IDS CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY                                	ID generation
CREATE TABLE IDS  (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID decimal(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
-- DROP TABLE LETTCCMMNCLCODE CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									공통분류코드
CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(60) ,
  CL_CODE_DC varchar(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;
-- DROP TABLE LETTCCMMNCODE CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									공통코드
CREATE TABLE LETTCCMMNCODE  (
  CODE_ID varchar(6) NOT NULL,
  CODE_ID_NM varchar(60) ,
  CODE_ID_DC varchar(200) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;
-- DROP TABLE LETTCCMMNDETAILCODE CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									공통상세코드
CREATE TABLE LETTCCMMNDETAILCODE  (
  CODE_ID varchar(6) NOT NULL,
  CODE varchar(15) NOT NULL,
  CODE_NM varchar(60) ,
  CODE_DC varchar(200) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;
-- DROP TABLE LETTNORGNZTINFO CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									조직정보
CREATE TABLE LETTNORGNZTINFO  (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(20) NOT NULL,
  ORGNZT_DC varchar(100) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
-- DROP TABLE LETTNAUTHORGROUPINFO CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									권한그룹정보
CREATE TABLE LETTNAUTHORGROUPINFO  (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(60) NOT NULL,
  GROUP_CREAT_DE char(20) NOT NULL,
  GROUP_DC varchar(100) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;
-- DROP TABLE LETTNEMPLYRINFO CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY									업무사용자정보
CREATE TABLE LETTNEMPLYRINFO  (
  EMPLYR_ID varchar(20) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(60) NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  EMPL_NO varchar(20) ,
  IHIDNUM varchar(200) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(20) ,
  HOUSE_ADRES varchar(100) ,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  HOUSE_END_TELNO varchar(4) ,
  AREA_NO varchar(4) ,
  DETAIL_ADRES varchar(100) ,
  ZIP varchar(6) ,
  OFFM_TELNO varchar(20) ,
  MBTLNUM varchar(20) ,
  EMAIL_ADRES varchar(50) ,
  OFCPS_NM varchar(60) ,
  HOUSE_MIDDLE_TELNO varchar(4) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(15) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(20) ,
  SBSCRB_DE TIMESTAMP(0) ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;
--DROP TABLE LETTNTMPLATINFO CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								템플릿
CREATE TABLE LETTNTMPLATINFO  (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,
  TMPLAT_NM varchar(255) ,
  TMPLAT_COURS varchar(2000) ,
  USE_AT char(1) ,
  TMPLAT_SE_CODE char(6) ,
  FRST_REGISTER_ID varchar(20) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  CONSTRAINT LETTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
--DROP TABLE LETTNBBSMASTER CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								게시판마스터
CREATE TABLE LETTNBBSMASTER  (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(255) NOT NULL,
  BBS_INTRCN varchar(2400) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER smallint NOT NULL,
  ATCH_POSBL_FILE_SIZE int ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP(0) NOT NULL,
  LAST_UPDUSR_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;
--DROP TABLE LETTNBBSUSE CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								게시판활용
CREATE TABLE LETTNBBSUSE  (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;

--DROP TABLE LETTNBBS CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								게시판
CREATE TABLE LETTNBBS (
  NTT_ID decimal(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO decimal(20,0) ,
  NTT_SJ varchar(2000) ,
  NTT_CN TEXT,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO bigint ,
  ANSWER_LC bigint ,
  SORT_ORDR int ,
  RDCNT bigint ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(20) ,
  NTCR_NM varchar(20) ,
  PASSWORD varchar(200) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) NOT NULL,								
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;
--DROP TABLE LETTNBBSMASTEROPTN CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								게시판마스터옵션
CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(20) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;
--DROP TABLE LETTNENTRPRSMBER CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								기업회원
CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(10) ,
  JURIRNO varchar(13) ,
  CMPNY_NM varchar(60) NOT NULL,
  CXFC varchar(50) ,
  ZIP varchar(6) ,
  ADRES varchar(100) ,
  ENTRPRS_MIDDLE_TELNO varchar(4) ,
  FXNUM varchar(20) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(50) NOT NULL,
  APPLCNT_IHIDNUM varchar(200) ,
  SBSCRB_DE TIMESTAMP(0) ,
  ENTRPRS_MBER_STTUS varchar(15) ,
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(100) ,
  ENTRPRS_END_TELNO varchar(4) ,
  AREA_NO varchar(4) ,
  APPLCNT_EMAIL_ADRES varchar(50) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
--DROP TABLE LETTNFILE CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								파일속성
CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT TIMESTAMP(0) NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
--DROP TABLE LETTNFILEDETAIL CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								파일상세정보
CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN bigint NOT NULL,
  FILE_STRE_COURS varchar(2000) NOT NULL,
  STRE_FILE_NM varchar(255) NOT NULL,
  ORIGNL_FILE_NM varchar(255) ,
  FILE_EXTSN varchar(20) NOT NULL,
  FILE_CN TEXT,
  FILE_SIZE int ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;
--DROP TABLE LETTNGNRLMBER CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								일반회원
CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(20) DEFAULT '' NOT NULL,
  PASSWORD varchar(200) NOT NULL,
  PASSWORD_HINT varchar(100) NOT NULL,
  PASSWORD_CNSR varchar(100) NOT NULL,
  IHIDNUM varchar(200) ,
  MBER_NM varchar(50) NOT NULL,
  ZIP varchar(6) ,
  ADRES varchar(100) ,
  AREA_NO varchar(4) ,
  MBER_STTUS varchar(15) ,
  DETAIL_ADRES varchar(100) ,
  END_TELNO varchar(4) ,
  MBTLNUM varchar(20) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(20) ,
  MBER_EMAIL_ADRES varchar(50) ,
  MIDDLE_TELNO varchar(4) ,
  SBSCRB_DE TIMESTAMP(0) ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
--DROP TABLE LETTNSCHDULINFO CASCADE CONSTRAINTS;
-- SQLINES LICENSE FOR EVALUATION USE ONLY								일정정보
CREATE TABLE LETTNSCHDULINFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar(20) ,
  SCHDUL_KND_CODE varchar(20) ,
  SCHDUL_BEGINDE char(20) ,
  SCHDUL_ENDDE char(20) ,
  SCHDUL_NM varchar(255) ,
  SCHDUL_CN varchar(2500) ,
  SCHDUL_PLACE varchar(255) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar(20) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM TIMESTAMP(0) ,
  FRST_REGISTER_ID varchar(20) ,
  LAST_UPDT_PNTTM TIMESTAMP(0) ,
  LAST_UPDUSR_ID varchar(20) ,
  REPTIT_SE_CODE char(3) ,
  CONSTRAINT LETTNSCHDULINFO_PK PRIMARY KEY (SCHDUL_ID)
) ;
CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;



-- (추가)                                                   업무사용자정보변경내역
CREATE TABLE LETTHEMPLYRINFOCHANGEDTLS (
    EMPLYR_ID VARCHAR(20) NOT NULL,
    CHANGE_DE CHAR(20) NOT NULL,
    ORGNZT_ID CHAR(20),
    GROUP_ID CHAR(20),
    EMPL_NO VARCHAR(20) NOT NULL,
    SEXDSTN_CODE CHAR(1),
    RTHDY CHAR(20),
    FXNUM VARCHAR(20),
    HOUSE_ADRES VARCHAR(100) NOT NULL,
    HOUSE_END_TELNO VARCHAR(4),
    AREA_NO VARCHAR(4),
    DETAIL_ADRES VARCHAR(100) NOT NULL,
    ZIP VARCHAR(6) NOT NULL,
    OFFM_TELNO VARCHAR(20),
    MBTLNUM VARCHAR(20) NOT NULL,
    EMAIL_ADRES VARCHAR(50),
    HOUSE_MIDDLE_TELNO VARCHAR(4),
    PSTINST_CODE CHAR(8),
    EMPLYR_STTUS_CODE VARCHAR(15) NOT NULL,
    ESNTL_ID CHAR(20),PRIMARY KEY(EMPLYR_ID,CHANGE_DE)
);

-- (추가)                                                   권한정보
CREATE TABLE LETTNAUTHORINFO (
    AUTHOR_CODE VARCHAR(30) NOT NULL PRIMARY KEY,
    AUTHOR_NM VARCHAR(60) NOT NULL,
    AUTHOR_DC VARCHAR(200),
    AUTHOR_CREAT_DE CHAR(20) NOT NULL
);

-- (추가)                                                   사용자보안설정
CREATE TABLE LETTNEMPLYRSCRTYESTBS (
    SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    MBER_TY_CODE VARCHAR(15),
    AUTHOR_CODE VARCHAR(30) NOT NULL,
    CONSTRAINT SYS_FK_104 FOREIGN KEY(SCRTY_DTRMN_TRGET_ID) REFERENCES LETTNEMPLYRINFO(EMPLYR_ID),
    CONSTRAINT SYS_FK_113 FOREIGN KEY(AUTHOR_CODE) REFERENCES LETTNAUTHORINFO(AUTHOR_CODE)
);